language: c

compiler:
  - clang
  - gcc
rvm:
  - "2.2.1"
os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential cmake libssl-dev flex bison doxygen check
  - ./install-libuv.sh
  - ./install-bison.sh
  - rvm use 2.2.1

script: ./cmake-build.sh

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
