language: c

compiler:
  - clang
  - gcc
os:
  - linux

before_install:
  - sudo apt-get update -yy
  - sudo apt-get install -y build-essential cmake libssl-dev flex bison doxygen check
  - ./install-libuv.sh


script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && make && make install

