language: c

compiler:
  - clang
  - gcc
os:
  - linux

before_install:
  - rvm install ruby-2.2
  - rvm use ruby-2.2
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential cmake libssl-dev flex doxygen check libjansson-dev
  - ./install-scripts/install-libuv.sh
  - ./install-scripts/install-bison.sh
  - ./install-scripts/install-cmake.sh

script: ./install-scripts/cmake-build.sh

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - CMAKE_BIN=$TRAVIS_BUILD_DIR/cmake-bin/bin
